env:
  es6: true
  node: true
  browser: true
  jest: true
plugins:
  - "@typescript-eslint"
  - filenames
  - prettier
  - promise
  - react
  - react-hooks
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:promise/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
settings:
  react:
    version: detect
rules:
  "@typescript-eslint/ban-types": 0 # to allow "{}" as a type
  "@typescript-eslint/camelcase": 0 #deprecated
  "@typescript-eslint/explicit-function-return-type": 0 # allow implicit return types
  "@typescript-eslint/explicit-module-boundary-types": 0
  "@typescript-eslint/interface-name-prefix": 0 # interfaces prefixed with "I" are perfectly fine
  "@typescript-eslint/no-empty-function": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-floating-promises": error
  "@typescript-eslint/no-inferrable-types": 0
  "@typescript-eslint/no-unused-vars": [error, { vars: all, ignoreRestSiblings: true }]
  "@typescript-eslint/no-useless-constructor": error
  "@typescript-eslint/no-var-requires": 0 # allow `require()`
  "@typescript-eslint/require-await": 0
  import/order: 0 # we use prettier import sorting by module
  no-console: 0
  no-restricted-imports:
    - error
    - paths:
        - name: bluebird
          message: Use native Promises and async/await instead!
  no-unused-expressions: 0 # use @typescript-eslint/no-unused-expressions instead
  no-unused-vars: 0 # use @typescript-eslint/no-unused-vars instead
  no-useless-constructor: 0 # use @typescript-eslint/no-useless-constructor instead
  prettier/prettier: error
  react-hooks/exhaustive-deps: error
  react-hooks/rules-of-hooks: error
overrides:
  - files: ["*.js"]
    rules:
      "@typescript-eslint/no-unsafe-assignment": 0 # avoid linter errors with .js files
      "@typescript-eslint/no-unsafe-call": 0
      "@typescript-eslint/no-unsafe-member-access": 0
      "@typescript-eslint/no-unsafe-return": 0
      "@typescript-eslint/no-unused-vars": 0